import random
import time
from typing import List

class MemoryGame:
    def __init__(self, difficulty: int):
        """
        Initialize the MemoryGame with a given difficulty level.

        :param difficulty: The level of difficulty, determines the sequence length.
        """
        self.difficulty = difficulty
        self.sequence = self.generate_sequence()

    def generate_sequence(self) -> List[int]:
        """
        Generate a list of random numbers based on the difficulty level.

        :return: A list of random numbers of length difficulty * 2.
        """
        #sequence = sorted([random.randint(1, 101) for _ in range(self.difficulty * 2)])
        sequence = sorted(random.sample(range(1, 102), self.difficulty * 2))
        return sequence

    def get_list_from_user(self) -> List[int]:
        """
        Prompt the user to input a list of numbers they remember.

        :return: A list of numbers entered by the user.
        """
        user_input = input(f"Enter the numbers you remember, separated by spaces: ")
        return list(map(int, user_input.split()))

    def is_list_equal(self, generated: List[int], user_list: List[int]) -> bool:
        """
        Compare two lists to check if they are equal, regardless of order.

        :param generated: The list generated by the game.
        :param user_list: The list provided by the user.
        :return: True if both lists contain the same numbers, otherwise False.
        """
        return sorted(generated) == sorted(user_list)

    def play(self) -> bool:
        """
        Play the memory game by displaying a sequence, getting user input, and checking if it matches.

        :return: True if the user wins, False if they lose.
        """
        print(f"Remember this sequence: {self.sequence}")
        time.sleep(0.7)  # Pause to allow the user to remember the sequence
        print("\033[H\033[J")  # Clear the console (only works in some environments)

        user_sequence = self.get_list_from_user()
        return self.is_list_equal(self.sequence, user_sequence)
